[package]
name = "rssbot-entities"
version = "0.2.0"
edition = "2021"

[lib]
name = "rssbot_entities"
path = "src/lib.rs"

[dependencies]
sea-orm = { workspace = true }
chrono = { workspace = true }
serde = { workspace = true }
